### ISSUE TITLE
Fix Procfile

### ISSUE THREAD

**Issue by gitsteph** [gitsteph/django_demo_2#13]
From `heroku logs`:
```
2018-05-08T01:22:45.511013+00:00 app[web.1]: Traceback (most recent call last):
2018-05-08T01:22:45.511014+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
2018-05-08T01:22:45.511016+00:00 app[web.1]: worker.init_process()
2018-05-08T01:22:45.511018+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/workers/base.py", line 129, in init_process
2018-05-08T01:22:45.511020+00:00 app[web.1]: self.load_wsgi()
2018-05-08T01:22:45.511021+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
2018-05-08T01:22:45.511022+00:00 app[web.1]: self.wsgi = self.app.wsgi()
2018-05-08T01:22:45.511024+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
2018-05-08T01:22:45.511026+00:00 app[web.1]: self.callable = self.load()
2018-05-08T01:22:45.511027+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
2018-05-08T01:22:45.511029+00:00 app[web.1]: return self.load_wsgiapp()
2018-05-08T01:22:45.511030+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
2018-05-08T01:22:45.511033+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/util.py", line 350, in import_app
2018-05-08T01:22:45.511032+00:00 app[web.1]: return util.import_app(self.app_uri)
2018-05-08T01:22:45.511035+00:00 app[web.1]: __import__(module)
2018-05-08T01:22:45.513343+00:00 app[web.1]: ModuleNotFoundError: No module named 'mysite.wsgi'
2018-05-08T01:22:45.513925+00:00 app[web.1]: [2018-05-08 01:22:45 +0000] [9] [INFO] Worker exiting (pid: 9)
```

**Comment by gitsteph** [comment]
Fixed with this PR: [https://github.com/gitsteph/django_demo_2/pull/14](https://github.com/gitsteph/django_demo_2/pull/14)
